### PR TITLE
Fix TextField type prop for antd  (closes #345)

### LINKED ISSUE #345: Textfield type="password" not working for antd style
The `'uniforms-antd/TextField` does not properly pass the `type` prop. See below.

For demonstration, I imported both antd and unstyled versions. The antd does not mask the input field as expected.  

```jsx
import AutoForm from 'uniforms-antd/AutoForm';
import TextField from 'uniforms-antd/TextField';
import TextField2 from 'uniforms-unstyled/TextField';

<AutoForm schema={loginFormSchema} onSubmit={submitLogin}>
 <TextField name="email" />
 <TextField name="password" type="password" />
 <TextField2 name="password" type="password" />
 <SubmitField>Submit</SubmitField>
</AutoForm>
```

### PR DESCRIPTION
**Pull request by purplecones**
Should fix #345 

@radekmie Let me know if this PR is okay.

I didn't see a need to touch `filterDOMProps` especially since its being used by all other style versions. It seems it was just a missed prop.

### CODE REVIEW

**Comment by purplecones** [comment]
Also, I'm not quite sure how I would fully test this locally by importing my version of the library into a sample react app. Right now I'm purely going by the jest test.

@radekmie how do you test new changes locally in a react app?

File: packages/uniforms-antd/src/TextField.js [hunk 1]
```diff
@@ -15,6 +15,7 @@ const Text = props =>
             placeholder={props.placeholder}
             ref={props.inputRef}
             value={props.value}
+            type={props.type}
```
Comment (radekmie) [inline packages/uniforms-antd/src/TextField.js]: Could you keep it ordered?

**Comment by radekmie** [comment]
Either by linking it to an existing app (symlink or ’npm link`) or in the demo app.

**Comment by radekmie** [comment]
I'll release it this weekend.
