### PR TITLE
Fixed preservation of mixin types (fixes #617).

### LINKED ISSUE #617: typescript error in uniforms-materialui
given 

```
import { AutoForm, AutoFields } from 'uniforms-material';

// later

   <AutoForm
         ...
        >
          <AutoFields />
        </AutoForm>

```

yields:

`JSX element type '{ [x: string]: any; }' is not a constructor function for JSX elements.`
`Type '{ [x: string]: any; }' is missing the following properties from type 'ElementClass': render, context, setState, forceUpdate, and 3 more.`

the generated type of `AutoForm` is:

```
declare const _default: {
    new (): {
        [x: string]: any;
    };
    [x: string]: any;
    Auto: (parent: any) => any;
};
export default _default;
```

it seems to complain about the type of `new()` which should be a react component

### PR DESCRIPTION
**Pull request by radekmie**
As reported in #617, `AutoForm` (other form components too) have non-JSX compatible types. With this change base class (`Component`) and mixin helpers are preserved. It's not an ideal solution but it'll do for now. In the future, we'd have to define `BaseForm` generic type and other forms should simply derive from it, reusing generics.

### CODE REVIEW

File: packages/uniforms/src/AutoForm.tsx [hunk 1]
```diff
@@ -4,10 +4,21 @@ import isEqual from 'lodash/isEqual';
...
+  T extends {
+    new (...args: any[]): BaseForm;
+    childContextTypes?: {};
+    defaultProps?: {};
+    displayName?: string;
+    propTypes?: {};
+  }
+>(parent: T): T & { Auto: typeof Auto } {
+  return class extends parent {
     static Auto: any = Auto;
```
Comment (kestarumper) [inline packages/uniforms/src/AutoForm.tsx]: Probably this `any` could be deleted.

File: packages/uniforms/src/BaseForm.tsx [hunk 2]
```diff
@@ -201,7 +201,7 @@ export default class BaseForm extends Component<any, any> {
     return changedKeys(root, valueA, valueB);
   }
 
-  getNativeFormProps() {
+  getNativeFormProps(): { [prop: string]: unknown } {
```
Comment (kestarumper) [inline packages/uniforms/src/BaseForm.tsx]: There is a nice utility type provided by typescript: [`Record<K,T>`](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkt). So you could use `Record<string, unknown>`.
