### PR TITLE
Fixed non-string labels (fixes #816).

### LINKED ISSUE #816: JSX labels are ignored in v3
The following code JSX renders a field without label:
```tsx
<TextField label={<span style={{ color: 'red' }}>Fancy Label</span>} />
```

### PR DESCRIPTION
**Pull request by radekmie**
This change fixes a bug reported in #816 as well as adds a broad set of tests for `label` handling. We should do the same for `placeholder`, but this will come separately.

### CODE REVIEW

**Comment by ArchiCroc** [comment]
This will be a nice addition. I was just troubleshooting this when I tried to pass i18n components for label, placeholder, and extra.

File: packages/uniforms/src/useField.tsx [hunk 1]
```diff
@@ -112,7 +113,8 @@ export function useField<
     ...props,
     label,
     name,
-    placeholder,
+    // TODO: Should we assert `typeof placeholder === 'string'`?
```
Comment (Monteth) [inline packages/uniforms/src/useField.tsx:116]: I don't think so, a placeholder in Antd is of the `ReactNode` type, so we shouldn't assert it so tight.

**Review by Monteth — APPROVED** [review]

File: packages/uniforms/src/useField.tsx (hunk 1 above)
Comment (radekmie) [reply packages/uniforms/src/useField.tsx:116]: That's true, however, widening `placeholder` from `string` to` ReactNode` will require casts or asserts in all HTML fields.
