### PR TITLE
Documentation: Add warnings about Ajv strict keywords to tutorial

### LINKED ISSUE #1145: Schema manipulation docs don't mention required non-default AJV configuration
## Problem
A guide in the docs suggests manipulating the schema with an `options` property to specify possible options for a SelectField (and auto-generate it): https://uniforms.tools/docs/tutorials-using-predefined-fields/#2-manipulating-the-schema)

However, AJV does not accept this when you pass it such a schema, since it is not valid JSON Schema. It hence breaks the example with this error:

```
 AJV: strict mode: unknown keyword: "options"
```

(thrown at `ajv.compile(schema);`)

## Steps to reproduce: 

CodeSandbox: https://codesandbox.io/s/peaceful-albattani-zj9hen
Only two minimal changes happened 
  1. Activate the JSONSchema example
  2. Add these lines to reflect the suggested code from the example (add a "select" field) https://codesandbox.io/s/peaceful-albattani-zj9hen?file=/schema/json-schema.tsx:923-1063

https://codesandbox.io/s/peaceful-albattani-zj9hen?file=/schema/json-schema.tsx

## Workarounds

1. ~~Disable strict AJV schema checking, but that defeats the purpose of AJV.~~
2. ~~Pass a different schema to the validator than to the JSON Schema Bridge. The validator schema should be purely valid JSON Schema and can not contain keywords like "options" or "uniforms". Those out-of-spec keywords can still be passed to the bridge. I did this successfully here in another similar example https://github.com/th0rgall/uniforms-test/blob/main/src/GuestSchema.ts#L69-L80~~
3. Supply extra `uniforms` and `options` keywords to AJV, see below.

## TODO

Update the docs so it explains how AJV should be configured in order for it to run the examples.

### PR DESCRIPTION
**Pull request by kestarumper**
## Description
This PR closes #1145 by adding warnings about Ajv strict keywords to the tutorial.

## Changes
- Added warning (caution) [admonitions](https://docusaurus.io/docs/next/markdown-features/admonitions) to [_Basic uniforms usage_](https://uniforms.tools/docs/tutorials-basic-uniforms-usage/) and [_Using predefined fields_](https://uniforms.tools/docs/tutorials-using-predefined-fields/) about Ajv strict keywords
- Modified `GuestSchema`(s) to use Ajv [utility types](https://ajv.js.org/guide/typescript.html#utility-types-for-schemas)

<details>
<summary>Click to see screenshots...</summary>

## Basic uniforms usage
image

## Using predefined fields
image

</details>

### CODE REVIEW

File: website/pages-parts/Tutorial/GuestSchema.ts [hunk 1]
```diff
@@ -17,19 +25,24 @@ const schema = {
...
 // <validator>
-const ajv = new Ajv({ allErrors: true, useDefaults: true });
+const ajv = new Ajv({
+  allErrors: true,
+  useDefaults: true,
+  keywords: ['uniforms'],
+});
 
-function createValidator(schema: object) {
+function createValidator(schema: JSONSchemaType<FormData>) {
```
Comment (radekmie) [inline website/pages-parts/Tutorial/GuestSchema.ts:42]: I'd rather see `createValidator` work with any `JSONSchemaType`.

File: website/pages-parts/Tutorial/GuestSchema.ts [hunk 2]
```diff
@@ -1,12 +1,20 @@
+// <schema>
 // <validator>
-import Ajv from 'ajv';
+import Ajv, { JSONSchemaType } from 'ajv';
 // </validator>
+// </schema>
```
Comment (radekmie) [inline website/pages-parts/Tutorial/GuestSchema.ts:5]: Is there an empty line between this `import` and the `interface` when rendered?

File: website/pages-parts/Tutorial/GuestSchema.ts [hunk 3]
```diff
@@ -1,12 +1,20 @@
...
 // <bridgeImport>
 import { JSONSchemaBridge } from 'uniforms-bridge-json-schema';
 // </bridgeImport>
 
 // <schema>
-const schema = {
+interface FormData {
```
Comment (radekmie) [inline website/pages-parts/Tutorial/GuestSchema.ts:11]: Let's use `type` instead.

File: website/pages-parts/Tutorial/GuestSchema.ts [hunk 4]
```diff
@@ -17,19 +25,24 @@ const schema = {
       type: 'integer',
       minimum: 0,
       maximum: 100,
+      nullable: true,
```
Comment (radekmie) [inline website/pages-parts/Tutorial/GuestSchema.ts:28]: Why `nullable`? It's not required, it should be enough.

**Review by radekmie — CHANGES_REQUESTED** [review]

**Review by wadamek65 — DISMISSED** [review]

File: website/pages-parts/Tutorial/GuestSchema.ts (hunk 2 above)
Comment (kestarumper) [reply website/pages-parts/Tutorial/GuestSchema.ts:5]: Yes, there is.
image

**Review by wadamek65 — APPROVED** [review]

**Review by radekmie — APPROVED** [review]
